apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: e2e-tests-go-pdjtkmsv
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/e2e-tests-go-pdjtkmsv:489bbbab7fdc9176b2a8e891e6ef2265e62bcb5d
          name: container-image
